import ScheduleTile from "./ScheduleTile";
import "./Schedules.css";

function Schedules() {

    function getBuses() {
        return [
            {
              name: "Bus1",
              type: "VE A/C Semi Sleeper(2+2)",
              departureTime: "10:00",
              departure: "Kozhikode",
              time: "04h 30m",
              arrivalTime: "12:00",
              arrival: "Thiruvananthapuram",
              fare: "600",
              seats: 4,
            },
            {
              name: "Bus2",
              type: "VE A/C Semi Sleeper(2+2)",
              departureTime: "10:00",
              departure: "Kozhikode",
              time: "04h 30m",
              arrivalTime: "10:00",
              arrival: "Thiruvananthapuram",
              fare: "600",
              seats: 4,
            },
            {
              name: "Bus3",
              type: "VE A/C Semi Sleeper(2+2)",
              departureTime: "10:00",
              departure: "Kozhikode",
              time: "04h 30m",
              arrivalTime: "10:00",
              arrival: "Thiruvananthapuram",
              fare: "600",
              seats: 4,
            },
            {
              name: "Bus3",
              type: "VE A/C Semi Sleeper(2+2)",
              departureTime: "10:00",
              departure: "Kozhikode",
              time: "04h 30m",
              arrivalTime: "10:00",
              arrival: "Thiruvananthapuram",
              fare: "600",
              seats: 4,
            },
            {
              name: "Bus3",
              type: "VE A/C Semi Sleeper(2+2)",
              departureTime: "10:00",
              departure: "Kozhikode",
              time: "04h 30m",
              arrivalTime: "10:00",
              arrival: "Thiruvananthapuram",
              fare: "600",
              seats: 4,
            },
            {
              name: "Bus3",
              type: "VE A/C Semi Sleeper(2+2)",
              departureTime: "10:00",
              departure: "Kozhikode",
              time: "04h 30m",
              arrivalTime: "10:00",
              arrival: "Thiruvananthapuram",
              fare: "600",
              seats: 4,
            },
            {
              name: "Bus4",
              type: "VE A/C Semi Sleeper(2+2)",
              departureTime: "10:00",
              departure: "Kozhikode",
              time: "04h 30m",
              arrivalTime: "10:00",
              arrival: "Thiruvananthapuram",
              fare: "600",
              seats: 4,
            },
            {
              name: "Bus4",
              type: "VE A/C Semi Sleeper(2+2)",
              departureTime: "10:00",
              departure: "Kozhikode",
              time: "04h 30m",
              arrivalTime: "10:00",
              arrival: "Thiruvananthapuram",
              fare: "600",
              seats: 4,
            },
            {
              name: "Bus4",
              type: "VE A/C Semi Sleeper(2+2)",
              departureTime: "10:00",
              departure: "Kozhikode",
              time: "04h 30m",
              arrivalTime: "10:00",
              arrival: "Thiruvananthapuram",
              fare: "600",
              seats: 4,
            },
            {
              name: "Bus4",
              type: "VE A/C Semi Sleeper(2+2)",
              departureTime: "10:00",
              departure: "Kozhikode",
              time: "04h 30m",
              arrivalTime: "10:00",
              arrival: "Thiruvananthapuram",
              fare: "600",
              seats: 4,
            },
            {
              name: "Bus4",
              type: "VE A/C Semi Sleeper(2+2)",
              departureTime: "10:00",
              departure: "Kozhikode",
              time: "04h 30m",
              arrivalTime: "10:00",
              arrival: "Thiruvananthapuram",
              fare: "600",
              seats: 4,
            },
            {
              name: "Bus4",
              type: "VE A/C Semi Sleeper(2+2)",
              departureTime: "10:00",
              departure: "Kozhikode",
              time: "04h 30m",
              arrivalTime: "10:00",
              arrival: "Thiruvananthapuram",
              fare: "600",
              seats: 4,
            },
        ];
    }

    return <div className="schedules">
        {getBuses().map((bus, index) => <ScheduleTile bus={bus} key={index}></ScheduleTile>)}
        </div>
}

export default Schedules;